services:

  application:
    build: docker/application
    env_file: .env
    working_dir: ${PROJECT_PATH}
    environment:
      PHP_IDE_CONFIG: serverName=${SERVER_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - ./:${PROJECT_PATH}:cached
    depends_on:
      - ${DB_HOST}

  database:
    image: postgres:${POSTGRES_VERSION}
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./docker/database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
